sudo: false
language: python
matrix:
    include:
      - python: 2.7
        env: TOXENV=py27
      - python: 3.3
        env: TOXENV=py33
      - python: 3.4
        env: TOXENV=py34
      - python: 3.5 # not yet pre-installed in Travis base image
        env: TOXENV=py35
      - python: 3.6 # not yet pre-installed in Travis base image
        env: TOXENV=py36
install:
  - pip install tox
script:
  - tox -e $TOXENV
